// purpose of this component is to show 1 image by itself
// creating a component expects to be passed a prop of the image obj
// we are going to use this component to render image to give enough space
// for the grid layout 
// the ref system are a system to give you direct access to single DOM
// element that is rendered by a component
// in order to createa ref we must define a constructor assign them to 
// the instance variables and then pass to a partiulcar JSX element props
// the ref system is how we somehow get a handle on a partiuclar elemtn
// generated by a tag

import React from 'react';

class ImageCard extends React.Component {
  constructor(props) {
      super(props);
      
      this.state = {spans: 0}

    this.imageRef = React.createRef();
  }

  componentDidMount() {
      this.imageRef.current.addEventListener('load', this.setSpans);
  }
    
    setSpans = () => {
        const height = this.imageRef.current.clientHeight;

        const spans = Math.ceil(height / 10);

        this.setState({ spans });
    };

  render() {
    const { description, urls } = this.props.image;

    return (
      <div style={{gridRowEnd: `span ${this.state.spans}`}}>
        <img ref={this.imageRef} alt={description} src={urls.regular} />
      </div>
    );
  }
}

export default ImageCard;
